# Generated by Django 4.2.1 on 2025-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('current_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('signuped_at', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_end_date', models.DateTimeField(blank=True, null=True)),
                ('date_matched', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_realized', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('home_lc_name', models.CharField(max_length=255)),
                ('home_mc_name', models.CharField(max_length=255)),
                ('opportunity_title', models.CharField(max_length=500)),
                ('opportunity_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('opportunity_earliest_start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('opportunity_latest_end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('programme_short_name', models.CharField(max_length=100)),
                ('programme_id', models.IntegerField()),
                ('home_lc_name_opportunity', models.CharField(max_length=255)),
                ('home_mc_name_opportunity', models.CharField(max_length=255)),
                ('host_lc_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expa_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('applicants_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('programme_short_name', models.CharField(max_length=100)),
                ('sub_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sdg_target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slots', models.IntegerField(default=0)),
                ('available_slots_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SignupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('profile_photo', models.URLField(blank=True, null=True)),
                ('home_lc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_mc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('selected_programmes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
