# Generated by Django 4.2.1 on 2025-10-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expa_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodioSignupOGTa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podio_item_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('home_lc', models.CharField(blank=True, max_length=255, null=True)),
                ('ep_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podio Signup OGTa',
                'verbose_name_plural': 'Podio Signups OGTa',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodioSignupOGTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podio_item_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('home_lc', models.CharField(blank=True, max_length=255, null=True)),
                ('ep_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podio Signup OGTe',
                'verbose_name_plural': 'Podio Signups OGTe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodioSignupOGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podio_item_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('home_lc', models.CharField(blank=True, max_length=255, null=True)),
                ('ep_id', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Podio Signup OGV',
                'verbose_name_plural': 'Podio Signups OGV',
                'ordering': ['-created_at'],
            },
        ),
    ]
